sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 
  - '9'
branches:
  only:
    - master
notifications:
  email: false
  script:
    - npm run validate
after_success:
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/